FROM python:3.6.9

WORKDIR /app

# RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

# CMD ["sh","-c","jupyter nbconvert --to notebook --execute hallo_gfaggle_hdfs.ipynb && jupyter nbconvert hallo_gfaggle_hdfs.nbconvert.ipynb --output-dir='results' --output='commit1.nbconvert.html'"]

